---
- name: Install Jenkins and Git
  hosts: your_target_host
  become: true
  tasks:
    - name: Download Jenkins repository file
      command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

    - name: Import Jenkins key
      command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Java OpenJDK 11
      command: amazon-linux-extras install java-openjdk11 -y

    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - fontconfig
        - java-11-openjdk
        - jenkins
        - git

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
